### ISSUE TITLE
增加支持网址https://w.linovelib.com/

### ISSUE THREAD

**Issue by Darkari** [Montaro2017/linovelib-downloader-v2#1]
你好，我试了试报了这样的错
```
java.lang.NullPointerException: Cannot invoke "org.jsoup.nodes.Element.text()" because the return value of "org.jsoup.nodes.Document.selectFirst(String)" is null
        at cn.montaro.linovelib.core.fetcher.Fetcher.fetchNovel(Fetcher.java:39)
        at cn.montaro.linovelib.cli.Main.start(Main.java:59)
        at cn.montaro.linovelib.cli.Main.main(Main.java:34)
```

 我尝试上https://www.linovelib.com 会显示access denied， 不过另一个网址https://w.linovelib.com 就没有问题，不知道可不可以增加这个网址的兼容呢？ 谢谢！

**Comment by Montaro2017** [comment]
你是开启了代理还是人在海外？
https://www.linovelib.com/似乎屏蔽了海外ip
如果改成w.linovelib.com整个项目要改的地方不少。
你可以先把你的日志文件发出来让我看一下

**Comment by Montaro2017** [comment]
先使用这个
https://github.com/Montaro2017/bili_novel_packer
